CREATE TABLE SETTINGS
(
  SETTING_KEY VARCHAR(32) PRIMARY KEY NOT NULL,
  SETTING_STRING VARCHAR(256),
  SETTING_INT INTEGER
);

CREATE TABLE ACCOUNTS
(
  ACCOUNT_UID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  ACCOUNT_NAME VARCHAR(64),
  ACCOUNT_ACTIVE BOOLEAN DEFAULT TRUE,
  ACCOUNT_TYPE INTEGER DEFAULT 0
);

CREATE TABLE IMPORTS
(
  IMPORT_UID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  IMPORT_DATETIME TIMESTAMP DEFAULT NOW(),
  IMPORT_ACCOUNT INTEGER,
  IMPORT_TYPE VARCHAR(1) DEFAULT 'I' NOT NULL,
  CONSTRAINT IMPORTS_ACCOUNT_FK FOREIGN KEY (IMPORT_ACCOUNT)
  REFERENCES ACCOUNTS (ACCOUNT_UID) ON DELETE CASCADE
);

CREATE TABLE TRANSACTIONS
(
  TRANSACTION_ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  TRANSACTION_IMPORT INTEGER,
  TRANSACTION_SOURCE_DATA VARCHAR(256),
  TRANSACTION_DATE DATE NOT NULL,
  TRANSACTION_DESCRIPTION VARCHAR(256),
  TRANSACTION_CARDHOLDER VARCHAR(64),
  TRANSACTION_DUPLICATE BOOLEAN NOT NULL,
  TRANSACTION_AMOUNT DECIMAL(16,2) NOT NULL,
  CONSTRAINT TRANSACTIONS_IMPORT_FK FOREIGN KEY (TRANSACTION_IMPORT)
  REFERENCES IMPORTS (IMPORT_UID) ON DELETE CASCADE
);

CREATE TABLE CATEGORIES
(
  CATEGORY_ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  CATEGORY_NAME VARCHAR(128),
  CATEGORY_TYPE VARCHAR(1) DEFAULT 'U' NOT NULL,
);

CREATE TABLE ALLOCATIONS
(
  ALLOCATION_ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  ALLOCATION_TRANSACTION INTEGER,
  ALLOCATION_CATEGORY INTEGER,
  ALLOCATION_MEMO VARCHAR(256),
  ALLOCATION_AMOUNT DECIMAL(16,2) NOT NULL,
  CONSTRAINT ALLOCATIONS_TRANSACTIONS_FK FOREIGN KEY (ALLOCATION_TRANSACTION)
  REFERENCES TRANSACTIONS (TRANSACTION_ID) ON DELETE CASCADE,
  CONSTRAINT ALLOCATIONS_CATEGORIES_FK FOREIGN KEY (ALLOCATION_CATEGORY)
  REFERENCES CATEGORIES (CATEGORY_ID) ON DELETE RESTRICT
);
