CREATE VIEW V_TRANSACTIONS AS SELECT
  TRANSACTIONS.*,
  IMPORTS.*,
  ACCOUNTS.*
  FROM TRANSACTIONS
  INNER JOIN IMPORTS ON TRANSACTIONS.TRANSACTION_IMPORT = IMPORTS.IMPORT_UID
  INNER JOIN ACCOUNTS ON IMPORTS.IMPORT_ACCOUNT = ACCOUNTS.ACCOUNT_UID;

